### ISSUE TITLE
plugin.xml

### ISSUE THREAD

**Issue by sengmow** [Coolerfall/Android-LunarView#12]
Hi

I tried to import the zip but the plugin.xml is missing. Appreciate you could share it if anyone has it.

Thanks.

**Comment by coolerfall** [comment]
What plugin.xml?

**Comment by sengmow** [comment]
I have been using cordova/phonegap plugin. As an example, the attached is
plugin.xml from alipay cordova plugin.

Thanks.

**Comment by coolerfall** [comment]
This is an AndroidStudio project.

**Comment by sengmow** [comment]
Ok, thanks.
