### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by microcian** [Coolerfall/Android-LunarView#3]
Can you see the 0 in month it start from 0 and end on 12, I don't and that's why showing wrong month
![screenshot_2016-07-05-12-13-51](https://cloud.githubusercontent.com/assets/4646811/16573762/3e5828c6-42aa-11e6-9a78-45cd40853d82.png)

**Comment by coolerfall** [comment]
The range of month is 0 - 11, just as the same as Calendar in Java.

**Comment by microcian** [comment]
so what is the issue ?? why this is occuring like this and how may I resolve this

**Comment by coolerfall** [comment]
You can check the demo, the month is range from 0 - 11. I have tested that.

**Comment by microcian** [comment]
I have already use this but did not work

**Comment by coolerfall** [comment]
![image](https://cloud.githubusercontent.com/assets/4580284/16580773/b6e9a64c-42d8-11e6-88e2-b95ae642b078.png)
You see, the month is just from Calendar, so I don't know how did you get 12.
And you can check https://github.com/Coolerfall/LunarLite too, it's based on LunarView.
